### ISSUE TITLE
Wrong assumptions decoding protocol

### ISSUE THREAD

**Issue by octo** [logstash-plugins/logstash-codec-collectd#13]
Hi, this is a follow-up to elastic/logstash#2014 and #6, which I don't believe to be fixed.

[The coment in line 424](https://github.com/logstash-plugins/logstash-codec-collectd/blob/master/lib/logstash/codecs/collectd.rb#L424) in _collectd.rb_ reads:

> We've reached a new plugin, delete everything except for the the host field, because there's only one per packet and the timestamp field, because that one goes in front of the plugin

Pretty much everything in this comment is wrong:
- The packet is fully incremental, i.e. you cannot clear _any_ field while in the middle of parsing it.
- The end of one metric and beginning of the following metric is indicated by the `VALUES` part, not the `PLUGIN` part. At this point all the fields of that metric are known and the metric should be copied to somewhere. You must not clear any fields afterwards though (with the exception of the values themselves, should your code set them in the struct / object / _$state_).
- The order of the fields is not defined, so long as sequential building of the state arrives at the right value. I.e. `PLUGIN` may well come _before_ the `TIME` – or not at all if it has the same value as the previous metric.
- If there are metrics from multiple hosts in one plugin, e.g. because when using the _network plugin_ in proxy (forwarding) mode or using the _SNMP plugin_, then `HOST` may well be repeated.

Creating a set of test vectors for the binary protocol is on my todo list and I'll happily drop a reference here once I have that.

Thanks for all your awesome work!

**Comment by jordansissel** [comment]
@octo Thanks for helping clarify this! <3 <3 <3

**Comment by untergeek** [comment]
Question: If true, doesn't this indicate that multithreading is a no-no?  We could potentially read packets out of order and therefore overwrite fields out of band...

**Comment by octo** [comment]
@untergeek what I outlined above only applies to _parsing a single packet_. State does not carry over to other packets, i.e. each packet starts with a clean slate / empty state.

**Comment by untergeek** [comment]
I believe these issues are addressed in #16 

Care to comment, @octo?

**Comment by octo** [comment]
@untergeek the Ruby is weak in me, but as far as I can tell the patch looks reasonable. I think we can close this bug for now and trust in actual users opening a new one if a corner case slipped through ;) Thanks for taking care of this!

**Comment by untergeek** [comment]
Thanks @octo
