### ISSUE TITLE
plugin_type persistence

### ISSUE THREAD

**Issue by untergeek** [logstash-plugins/logstash-codec-collectd#6]
From https://github.com/elasticsearch/logstash/issues/2014

Testing confirms this.

If two plugins use the same type_instance name, as is the case with df and memory plugin types, collectd saves traffic by not re-sending the value.  This persistence needs to be added to prevent this edge case.

**Comment by iivarih** [comment]
Do they really use same plugin_type? My understanding is that they differ.

typemap has this:
PLUGIN_TYPE     => "plugin",

I might be wrong of course, not familiar with this stuff...

**Comment by iivarih** [comment]
so you mean type_instance (not plugin_type) right?

**Comment by untergeek** [comment]
Fixed the text in the issue.  Thanks for catching it.
